#!name=哔哩哔哩
#!desc=过滤哔哩哔哩广告
#!author=RuCu6[https://github.com/RuCu6], kokoryh[https://github.com/kokoryh], Maasea[https://github.com/Maasea], 可莉🅥[https://github.com/luestr/ProxyResource/blob/main/README.md]
#!icon=https://raw.githubusercontent.com/sooyaaabo/Loon/main/Icon/App-Icon/BilibiliRed.png
#!openUrl=https://apps.apple.com/app/id736536022
#!tag=去广告
#!homepage=https://github.com/sooyaaabo/Egern
#!date=2025-01-01 00:00

[Rule]
# 开屏广告
URL-REGEX,"^http:\/\/upos-sz-static\.bilivideo\.com\/ssaxcode\/\w{2}\/\w{2}\/\w{32}-1-SPLASH",REJECT-DICT
URL-REGEX,"^http:\/\/[\d\.]+:8000\/v1\/resource\/\w{32}-1-SPLASH",REJECT-DICT

[URL Rewrite]
# 开屏广告
^https:\/\/(?:api\.bilibili\.com\/x\/mengqi\/v1\/resource|app\.bilibili\.com\/x\/resource\/peak\/download) - reject-dict
# 满意度调研
^https:\/\/api\.bilibili\.com\/x\/v2\/dm\/qoe\/show\? - reject-dict
# 大会员广告
^https:\/\/api\.bilibili\.com\/x\/vip\/ads\/materials\? - reject-dict
# 直播广告
^https:\/\/api\.live\.bilibili\.com\/xlive\/e-commerce-interface\/v1\/ecommerce-user\/get_shopping_info\? - reject-dict
# 屏蔽默认搜索框关键词
^https:\/\/(?:app\.bilibili\.com|grpc\.biliapi\.net)\/bilibili\.app\.interface\.v1\.Search\/DefaultWords$ - reject-dict
# 流量卡推荐
^https:\/\/(?:app\.bilibili\.com|grpc\.biliapi\.net)\/bilibili\.app\.view\.v1\.View\/TFInfo$ - reject-dict
# IP请求、地理位置请求 //api.bilibili.com
^https:\/\/app\.bilibili\.com\/x\/resource\/ip - reject-dict
^https:\/\/api\.bilibili\.com\/x\/web-interface\/zone\?jsonp - reject-dict
# 移除直播间链接跟踪参数
(^https:\/\/live\.bilibili\.com\/\d+)(\/?\?.*) $1 307
# 移除视频链接跟踪参数
(^https:\/\/(?:www|m)\.bilibili\.com\/video\/(?:BV\w{10}|av\d{9}))(\/?\?.*) $1 307

[Script]
移除皮肤推送 = type=http-response, pattern=^https:\/\/app\.bilibili\.com\/x\/resource\/show\/skin\?, script-path=https://raw.githubusercontent.com/Script-Hub-Org/Script-Hub/main/scripts/body-rewrite.js, requires-body=true, max-size=-1, timeout=30, argument=%5B%5B%22json-del%22%2C%5B%22data.common_equip%22%5D%5D%5D

# 移除右上角活动入口
移除右上角活动入口 = type=http-request, pattern=^https:\/\/app\.bilibili\.com\/x\/resource\/top\/activity\?, script-path=https://raw.githubusercontent.com/Script-Hub-Org/Script-Hub/main/scripts/echo-response.js, timeout=60, argument=text=%7B%22code%22%3A-404%2C%22message%22%3A%22-404%22%2C%22ttl%22%3A1%2C%22data%22%3Anull%7D&status-code=200

# 移除热搜广告
移除热搜广告 = type=http-request, pattern=^https:\/\/app\.bilibili\.com\/x\/v2\/search\/square, script-path=https://raw.githubusercontent.com/Script-Hub-Org/Script-Hub/main/scripts/echo-response.js, timeout=60, argument=text=%7B%22code%22%3A0%2C%22message%22%3A%220%22%2C%22ttl%22%3A1%2C%22data%22%3A%5B%7B%22type%22%3A%22history%22%2C%22title%22%3A%22%E6%90%9C%E7%B4%A2%E5%8E%86%E5%8F%B2%22%7D%5D%7D&status-code=200

移除热搜广告 = type=http-request, pattern=^https:\/\/app\.bilibili\.com\/x\/(?:resource\/top\/activity|v2\/search\/square), script-path=https://raw.githubusercontent.com/Script-Hub-Org/Script-Hub/main/scripts/echo-response.js, timeout=60, argument=text=%7B%22code%22%3A-404%2C%22message%22%3A%22-404%22%2C%22ttl%22%3A1%2C%22data%22%3Anull%7D&status-code=200

# Proto处理
移除动态页面广告 = type=http-response, pattern=^https:\/\/(?:app\.bilibili\.com|grpc\.biliapi\.net)\/bilibili\.app\.dynamic\.v2\.Dynamic\/DynAll$, script-path=https://raw.githubusercontent.com/kokoryh/Script/master/js/bilibili.protobuf.js, requires-body=true, binary-body-mode=true, argument=[{showUpList}]

移除青少年模式弹窗 = type=http-response, pattern=^https:\/\/(?:app\.bilibili\.com|grpc\.biliapi\.net)\/bilibili\.app\.interface\.v1\.Teenagers\/ModeStatus$, script-path=https://raw.githubusercontent.com/kokoryh/Script/master/js/bilibili.protobuf.js, requires-body=true, binary-body-mode=true

移除热门话题 = type=http-response, pattern=^https:\/\/(?:app\.bilibili\.com|grpc\.biliapi\.net)\/bilibili\.app\.show\.v1\.Popular\/Index$, script-path=https://raw.githubusercontent.com/kokoryh/Script/master/js/bilibili.protobuf.js, requires-body=true, binary-body-mode=true

移除播放页面广告 playview = type=http-response, pattern=^https:\/\/(?:app\.bilibili\.com|grpc\.biliapi\.net)\/bilibili\.app\.playurl\.v1\.PlayURL\/PlayView$, script-path=https://raw.githubusercontent.com/kokoryh/Script/master/js/bilibili.protobuf.js, requires-body=true, binary-body-mode=true

移除播放页面广告 playerunite = type=http-response, pattern=^https:\/\/(?:app\.bilibili\.com|grpc\.biliapi\.net)\/bilibili\.app\.playerunite\.v1\.Player\/PlayViewUnite$, script-path=https://raw.githubusercontent.com/kokoryh/Script/master/js/bilibili.protobuf.js, requires-body=true, binary-body-mode=true

移除播放页面广告 view = type=http-response, pattern=^https:\/\/(?:app\.bilibili\.com|grpc\.biliapi\.net)\/bilibili\.app\.view\.v1\.View\/(?:View|ViewProgress|TFInfo)$, script-path=https://raw.githubusercontent.com/kokoryh/Script/master/js/bilibili.protobuf.js, requires-body=true, binary-body-mode=true

移除播放页面广告 viewunite = type=http-response, pattern=^https:\/\/(?:app\.bilibili\.com|grpc\.biliapi\.net)\/bilibili\.app\.viewunite\.v1\.View\/(?:View|ViewProgress|RelatesFeed)$, script-path=https://raw.githubusercontent.com/kokoryh/Script/master/js/bilibili.protobuf.js, requires-body=true, binary-body-mode=true

移除交互式弹幕 = type=http-response, pattern=^https:\/\/(?:app\.bilibili\.com|grpc\.biliapi\.net)\/bilibili\.community\.service\.dm\.v1\.DM\/(?:DmView|DmSegMobile)$, script-path=https://raw.githubusercontent.com/kokoryh/Script/master/js/bilibili.protobuf.js, requires-body=true, binary-body-mode=true

移除评论区广告 = type=http-response, pattern=^https:\/\/(?:app\.bilibili\.com|grpc\.biliapi\.net)\/bilibili\.main\.community\.reply\.v1\.Reply\/MainList$, script-path=https://raw.githubusercontent.com/kokoryh/Script/master/js/bilibili.protobuf.js, requires-body=true, binary-body-mode=true

移除搜索结果广告 = type=http-response, pattern=^https:\/\/(?:app\.bilibili\.com|grpc\.biliapi\.net)\/bilibili\.polymer\.app\.search\.v1\.Search\/SearchAll$, script-path=https://raw.githubusercontent.com/kokoryh/Script/master/js/bilibili.protobuf.js, requires-body=true, binary-body-mode=true

移除搜索框关键词 = type=http-response, pattern=^https:\/\/(?:app\.bilibili\.com|grpc\.biliapi\.net)\/bilibili\.app\.interface\.v1\.Search\/DefaultWords$, script-path=https://raw.githubusercontent.com/kokoryh/Script/master/js/bilibili.protobuf.js, requires-body=true, binary-body-mode=true

# JSON配置处理
移除开屏广告 = type=http-response, pattern=^https:\/\/app\.bilibili\.com\/x\/v2\/splash\/(?:brand\/list|event\/list2|list|show), script-path=https://kelee.one/Resource/Script/Bilibili/Bilibili_remove_ads.js, requires-body=true

移除首页推荐广告 = type=http-response, pattern=^https:\/\/app\.bilibili\.com\/x\/v2\/feed\/index, script-path=https://kelee.one/Resource/Script/Bilibili/Bilibili_remove_ads.js, requires-body=true

精简首页顶部标签 = type=http-response, pattern=^https:\/\/app\.bilibili\.com\/x\/resource\/show\/tab\/v2\?, script-path=https://kelee.one/Resource/Script/Bilibili/Bilibili_remove_ads.js, requires-body=true

移除热搜广告 = type=http-response, pattern=^https:\/\/app\.bilibili\.com\/x\/v2\/search\/square\?, script-path=https://kelee.one/Resource/Script/Bilibili/Bilibili_remove_ads.js, requires-body=true

移除观影页广告 = type=http-response, pattern=^https:\/\/api\.bilibili\.com\/pgc\/page\/(?:bangumi|cinema\/tab), script-path=https://kelee.one/Resource/Script/Bilibili/Bilibili_remove_ads.js, requires-body=true

移除直播间广告 = type=http-response, pattern=^https:\/\/api\.live\.bilibili\.com\/xlive\/app-room\/v1\/index\/getInfoByRoom\?, script-path=https://kelee.one/Resource/Script/Bilibili/Bilibili_remove_ads.js, requires-body=true

精简我的页面 = type=http-response, pattern=^https:\/\/app\.bilibili\.com\/x\/v2\/account\/(?:mine|myinfo), script-path=https://kelee.one/Resource/Script/Bilibili/Bilibili_remove_ads.js, requires-body=true

[MITM]
hostname = %APPEND% ap?.bilibili.com, grpc.biliapi.net, www.bilibili.com, m.bilibili.com, *live.bilibili.com