#!name=滴滴出行
#!desc=过滤滴滴出行广告
#!author=ZenmoFeiShi[https://github.com/ZenmoFeiShi], 可莉🅥[https://github.com/luestr/ProxyResource/blob/main/README.md]
#!icon=https://raw.githubusercontent.com/sooyaaabo/Loon/main/Icon/App-Icon/DiDi.png
#!openUrl=https://apps.apple.com/app/id554499054
#!tag=去广告
#!homepage=https://github.com/sooyaaabo/Egern
#!date=2025-09-11 17:00

[Rule]
# 拦截广告下发
DOMAIN,gwp.xiaojukeji.com,REJECT
DOMAIN,adtrack.xiaojukeji.com,REJECT
AND,((IP-ASN,45090,no-resolve),(DEST-PORT,25641),(PROTOCOL,TCP)),REJECT
AND,((IP-ASN,63646,no-resolve),(DEST-PORT,25641),(PROTOCOL,TCP)),REJECT
IP-CIDR,113.46.225.8/32,REJECT,no-resolve
IP-CIDR,113.46.225.9/32,REJECT,no-resolve
IP-CIDR,116.85.1.0/32,REJECT,no-resolve
IP-CIDR,116.85.1.17/32,REJECT,no-resolve
IP-CIDR,116.85.1.22/32,REJECT,no-resolve
IP-CIDR,116.85.2.15/32,REJECT,no-resolve
IP-CIDR,116.85.3.25/32,REJECT,no-resolve
IP-CIDR,116.85.3.37/32,REJECT,no-resolve
IP-CIDR,120.234.72.27/32,REJECT,no-resolve
IP-CIDR,120.241.142.13/32,REJECT,no-resolve
IP-CIDR,120.241.143.6/32,REJECT,no-resolve
IP-CIDR,120.241.143.11/32,REJECT,no-resolve
IP-CIDR,120.241.143.129/32,REJECT,no-resolve
IP-CIDR,120.241.143.131/32,REJECT,no-resolve
IP-CIDR,123.207.209.39/32,REJECT,no-resolve
IP-CIDR,123.207.209.60/32,REJECT,no-resolve
IP-CIDR,139.199.240.12/32,REJECT,no-resolve
IP-CIDR,139.199.240.15/32,REJECT,no-resolve
IP-CIDR,157.122.213.3/32,REJECT,no-resolve
IP-CIDR,157.255.76.17/32,REJECT,no-resolve
IP-CIDR,157.255.76.19/32,REJECT,no-resolve
IP-CIDR,162.14.157.2/32,REJECT,no-resolve
IP-CIDR,162.14.157.24/32,REJECT,no-resolve

[Body Rewrite]
http-response-jq ^https:\/\/conf\.diditaxi\.com\.cn\/homepage\/v1\/core\? '.data.disorder_cards.bottom_nav_list.data |= map(select(.id == "home_page" or .id == "user_center")) | .data.order_cards.nav_list_card.data |= map(select(.nav_id == "dache_anycar" or .nav_id == "carmate" or .nav_id == "driverservice" or .nav_id == "yuancheng" or .nav_id == "bike"))'
http-response-jq ^https:\/\/res\.xiaojukeji\.com\/resapi\/activity\/mget\? 'delpaths([["data","mult_home_banner"]])'
http-response-jq ^https:\/\/common\.diditaxi\.com\.cn\/common\/v5\/usercenter\/layout 'del(.data.instances.center_marketing_card, .data.instances.center_tool_card, .data.instances.center_widget_list, .data.instances.center_res_light_guide) | .data.instances.center_wallet_finance_card.data.view_info |= map(select(.title == "优惠卡券"))'
http-response-jq ^https:\/\/api\.udache\.com\/gulfstream\/porsche\/v1\/dache_homepage_layout\? 'delpaths([["data","instances","car_icon_01","data","icon_info_new_agreement"]])'
http-response-jq ^https:\/\/api\.udache\.com\/gulfstream\/passenger-center\/v2\/other\/pInTripLayout '.data.order_components |= map(select(.name != "passenger_common_casper"))'
http-response-jq ^https:\/\/as\.xiaojukeji\.com\/ep\/as\/toggles\? '.data |= map(if .name|IN("daijia_journey_new_tcp_switch","daijia_tcp_init","daijia_tcp_msg_encrypt","daijia_tcp_site_info","daijia_tcp_site_report")then.allow=false else. end)'

[Map Local]
# 活动弹窗
^https:\/\/res\.xiaojukeji\.com\/resapi\/activity\/mget data-type=text data="{}" status-code=200 header="Content-Type:application/json"

# 顶部活动通知
^https:\/\/lion\.didialift\.com\/broker\/\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"

# 重逢专属福利
^https:\/\/conf\.diditaxi\.com\.cn\/homepage\/v1\/other\/slow\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"

# 首页 - 登录奖励广告、促销提示栏、乘车码、主要轮播广告、车主服务入口、横幅广告
^https:\/\/conf\.diditaxi\.com\.cn\/homepage\/v1\/other\/fast data-type=text data="{}" status-code=200 header="Content-Type:application/json"

# 首页 - 拼车功能运营卡片配置数据
^https:\/\/ct\.xiaojukeji\.com\/agent\/v3\/feeds\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"

# 打车页面 - 运营卡片配置数据
^https:\/\/conf\.diditaxi\.com\.cn\/dynamic\/conf data-type=text data="{}" status-code=200 header="Content-Type:application/json"

[MITM]
hostname = %APPEND% res.xiaojukeji.com, lion.didialift.com, conf.diditaxi.com.cn, common.diditaxi.com.cn, ct.xiaojukeji.com, api.udache.com, 113.46.225.4, 113.46.225.5, 116.85.2.14, 116.85.2.15, 123.207.209.41, 123.207.209.42, 123.207.209.56, 123.207.209.57, 123.207.209.142, 123.207.209.143, 123.207.209.160, 123.207.209.177, 2402:4e00:4040::15, 2402:4e00:4040::16, 2402:4e00:4040::5, 2402:4e00:4040::b, 2402:4e00:4040::c, 2402:4e00:4040::f, 2402:840:d001::3, 2402:840:d001::4