#!name=萤石云视频
#!desc=过滤萤石云视频广告
#!author=可莉🅥[https://github.com/luestr/ProxyResource/blob/main/README.md]
#!icon=https://raw.githubusercontent.com/sooyaaabo/Loon/main/Icon/App-Icon/Ezviz.png
#!openUrl=https://apps.apple.com/app/id571195405
#!tag=去广告
#!homepage=https://github.com/sooyaaabo/Egern
#!date=2025-05-14 22:00

[URL Rewrite]
^https:\/\/api\.ys7\.com\/api\/ads - reject
^https:\/\/i\.ys7\.com\/api\/user\/tabList - reject-dict
# 我的页面 - 轮播图推广
^https:\/\/api\.ys7\.com\/v3\/config\/service\/entrance\/bannerInfo - reject-dict
# 智能 - 玩法 - 精选专题
^https:\/\/api\.ys7\.com\/v3\/intelligent-app\/apps\/linkage - reject-dict
^https:\/\/api\.ys7\.com\/v3\/configurations\/gray\/info\?grayTypes=185 - reject-dict
# 天气视频
^https:\/\/api\.ys7\.com\/v3\/videoclips\/square\/video\/query - reject-dict

[MITM]
hostname = %APPEND% api.ys7.com, i.ys7.com