#!name=迅雷
#!desc=过滤迅雷广告，解锁部分会员功能。
#!author=可莉🅥[https://github.com/luestr/ProxyResource/blob/main/README.md], Marol62926[https://github.com/Marol62926]
#!icon=https://raw.githubusercontent.com/sooyaaabo/Loon/main/Icon/App-Icon/ThunderCloudDisk.png
#!openUrl=https://apps.apple.com/app/id1503466530
#!tag=去广告, 解锁会员
#!homepage=https://github.com/sooyaaabo/Egern
#!date=2025-05-13 22:00

[URL Rewrite]
# 首页 - 横幅推广
^https:\/\/api-shoulei-ssl\.xunlei\.com\/flowhub\/v1\/slots:batchGet$ - reject-dict

[Script]
# 解锁迅雷会员
解锁迅雷会员 = type=http-response, pattern=^https:\/\/xluser-ssl\.xunlei\.com\/xluser\.core\.login\/v3\/getuserinfo, script-path=https://raw.githubusercontent.com/Marol62926/MarScrpt/main/xunlei.js, requires-body=true

# 精简我的页面
精简我的页面 = type=http-response, pattern=^https:\/\/conf-m-ssl\.xunlei\.com\/external\/, script-path=https://kelee.one/Resource/Script/XunLei/XunLei_remove_ads.js, requires-body=true

[MITM]
hostname = %APPEND% api-shoulei-ssl.xunlei.com, conf-m-ssl.xunlei.com, xluser-ssl.xunlei.com