#!name=喜马拉雅
#!desc=过滤喜马拉雅广告
#!author=可莉🅥[https://github.com/luestr/ProxyResource/blob/main/README.md]
#!icon=https://raw.githubusercontent.com/sooyaaabo/Loon/main/Icon/App-Icon/Ximalaya.png
#!openUrl=https://apps.apple.com/app/id876336838
#!tag=去广告
#!homepage=https://github.com/sooyaaabo/Egern
#!date=2025-05-14 22:00

[Rule]
DOMAIN,adse.ximalaya.com,REJECT
DOMAIN,adsehera.ximalaya.com,REJECT
DOMAIN,adse.wsa.ximalaya.com,REJECT
DOMAIN,adbehavior.ximalaya.com,REJECT
DOMAIN,adbehavior.wsa.ximalaya.com,REJECT

[URL Rewrite]
# 搜索词
^https:\/\/(?:search|searchwsa)\.ximalaya\.com\/hub\/(guideWord|hotWord)V\d\/ - reject-dict
^https:\/\/(?:mobile|mobilehera|mobwsa)\.ximalaya\.com\/discovery-feed\/v\d\/scene\/listen\/refresh\? - reject-dict
# 首页 - 右上角红包
^https:\/\/(?:m|mwsa)\.ximalaya\.com\/x-web-activity\/signIn\/getHomePageSignInInfo\/ - reject-dict
# 订阅 - 订阅推荐
^https:\/\/(?:mobile|mobilehera|mobwsa)\.ximalaya\.com\/subscribe\/v\d\/subscribe\/tagAlbumList$ - reject-dict
# 订阅 - 追更 -追更推荐
^https:\/\/(?:mobile|mobilehera|mobwsa)\.ximalaya\.com\/track-feed\/v\d\/chase\/recommend\/ - reject-dict
# 订阅 - 关注 - 精选节目推荐
^https:\/\/(?:mobile|mobilehera|mobwsa)\.ximalaya\.com\/social-web\/follow-stream\/category\/\d+$ - reject-dict
# 播放器 - 推荐
^https:\/\/(?:mobile|mobilehera|mobwsa)\.ximalaya\.com\/mobile-playpage\/playpage\/recommendContentV\d\/ - reject-dict
# 播放器 - 推广
^https:\/\/(?:mobile|mobilehera|mobwsa)\.ximalaya\.com\/mobile-playpage\/playpage\/recommend\/resource\/allocation\/ - reject-dict
# 弹窗
^https:\/\/(?:mobile|mobilehera|mobwsa)\.ximalaya\.com\/firework-portal\/v\d+\/sync\? - reject-dict
^https:\/\/(?:mobile|mobilehera|mobwsa)\.ximalaya\.com\/business-sale-promotion-guide-mobile-web\/popup\/ - reject-dict
# 皮肤配置
^https:\/\/(?:mobile|mobilehera|mobwsa)\.ximalaya\.com\/app-skin-service\/skin\/setting\/info\/ - reject-dict
# 我的页面 - 直播提醒气泡
^https:\/\/livewsa\.ximalaya\.com\/lamia\/v1\/subscribe\/status$ - reject-dict
# 我的页面 - 本地 - 你可能感兴趣的内容
^https:\/\/(?:mobile|mobilehera|mobwsa)\.ximalaya\.com\/subscribe\/v\d\/subscribe\/recommend\? - reject-dict
# 我的页面 - 已购 - 为你推荐
^https:\/\/(?:mobile|mobilehera|mobwsa)\.ximalaya\.com\/mobile-user\/v\d\/purchased\/recommend\/ - reject-dict

[Script]
移除喜马拉雅全局广告 = type=http-response, pattern=^https:\/\/(?:mobile|mobilehera|mobwsa)\.ximalaya\.com\/football-portal\/diff2\/batch\?, script-path=https://raw.githubusercontent.com/Script-Hub-Org/Script-Hub/main/scripts/body-rewrite.js, requires-body=true, max-size=-1, timeout=30, argument=%5B%5B%22json-del%22%2C%5B%22json.ad%22%2C%22json.toc%22%5D%5D%5D

移除圈子推荐广告 = type=http-request, pattern=^https:\/\/(?:m|mwsa)\.ximalaya\.com\/community\/square\/v\d\/stream\?, script-path=https://raw.githubusercontent.com/Script-Hub-Org/Script-Hub/main/scripts/echo-response.js, timeout=60, argument=text=%7B%22data%22%3A%7B%22cards%22%3A%5B%7B%22content%22%3A%7B%7D%2C%22type%22%3A%22RECOMMENDS%22%7D%5D%7D%2C%22ret%22%3A0%7D&status-code=200

移除我的页面广告 = type=http-response, pattern=^https:\/\/(?:mobile|mobilehera|mobwsa)\.ximalaya\.com\/mobile-user\/v\d\/homePage\/, script-path=https://raw.githubusercontent.com/Script-Hub-Org/Script-Hub/main/scripts/body-rewrite.js, requires-body=true, max-size=-1, timeout=30, argument=%5B%5B%22json-del%22%2C%5B%22data.freeListenV2%22%5D%5D%5D

[MITM]
hostname = %APPEND% gslbali.ximalaya.com, search.ximalaya.com, searchwsa.ximalaya.com, mobile.ximalaya.com, mobilehera.ximalaya.com, mobwsa.ximalaya.com, m.ximalaya.com, mwsa.ximalaya.com