name: Replace data in .module Files

on:
  workflow_dispatch:
  # schedule:
    # - cron: "30 * * * *"

permissions:
  actions: write  
  contents: write  

jobs:
  replace-date:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          repository: sooyaaabo/Egern
          path: Egern
          token: ${{ secrets.GITHUB_TOKEN }} 
        
      - name: Set timezone to China/Shanghai
        run: |
          sudo timedatectl set-timezone Asia/Shanghai

      - name: Find and replace date in .module files
        run: |
          #!/bin/bash
          # 使用 find 命令查找所有 .module 文件
          find . -type f -name "*.module" | while read file; do
            # 使用 sed 替换文件中的 #!date= 开头的行
            sed -i 's|#!date=.*|#!date=2025-02-04 17:00|' "$file"
          done
          
      - name: Commit changes
        run: |
          cd Egern
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Update Data In Module" || echo "No changes to commit"
          git push
